# Generated by Django 3.2.12 on 2022-12-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_evjarat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='evjarat',
            field=models.CharField(max_length=200),
        ),
    ]
