# Generated by Django 3.2.12 on 2022-12-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_evjarat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='allapot',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='evjarat',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='post',
            name='kivitel',
            field=models.CharField(max_length=20),
        ),
    ]
