# Generated by Django 3.2.12 on 2022-12-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20221230_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kmora',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
    ]
