# Generated by Django 3.2.12 on 2022-12-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20221230_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ajtok',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
