# Generated by Django 3.2.12 on 2022-12-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20221230_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='szin',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
