# Generated by Django 3.2.12 on 2022-12-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_szin'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='csomagtarto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='klima',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
